### ISSUE TITLE
webapp tests are failing

### ISSUE THREAD

**Issue by OskarD** [phax/peppol-smp-server#12]
While compiling the project using maven, I get this test failure:
`Failed tests: 
  ServiceGroupInterfaceTest.testCreateAndDeleteServiceGroup:174->_testResponse:108 500 is not in [200, 404]
  ServiceMetadataInterfaceTest.testCreateAndDeleteRedirect:324->_testResponse:123 [200, 404] does not contain 500
  ServiceMetadataInterfaceTest.testCreateAndDeleteServiceInformation:233->_testResponse:123 [200, 404] does not contain 500
`

I can post the stack if you want, but you should get the same result if you try to compile a clean version of the repo

**Comment by phax** [comment]
Hi Oskar!
Thanks for the info. For me the tests are running flawlessly.
Maybe the problem is, that you need a MySQL-DB for compiling the stuff (name: smp, user: smp, password: smp, server: localhost:3306).
Do you have that?
But good point, I will try to adopt the tests, so that they are not failing, even if no DB is present.
// Philip

**Comment by OskarD** [comment]
Hello Philip!
I think you are right, it must be because I have no MySQL server running on the compiling server. It would be better if the tests don't require MySQL, thanks!
