### ISSUE TITLE
Wrong keystore path in error message

### ISSUE THREAD

**Issue by OskarD** [phax/peppol-smp-server#15]
After deploying my webapp, I get this message:

> Failed to load keystore from path 'keystore/keystore.jks'. Seems like the keystore file does not exist. Technical details: Failed to open key store 'keystore/keystore.jks'

I changed the keystore path in my webapp.properties file, that is a different one. I don't know if the problem is that the message is incorrectly displayed, or if its not attempting to load the correct keystore.

**Comment by phax** [comment]
The keystore must be referenced from `smp-server.properties` and not from the other file. The difference exists because the mentioned one is for the SMP only whereas the `webapp.properties` is "only" for the UI.
If you are referencing the `smp-server.properties` file via a System property you need to make sure that the path to the keystore is also absolute!

**Comment by OskarD** [comment]
Yes, sorry, I meant the `smp-server.properties` file!

Why does it have to be absolute now? The relative path `keystore/storename.jks` worked well before!

Either way, the message displayed isn't the name of the keystore I referenced in my properties

**Comment by phax** [comment]
The resolution of the keystore happens in the following order:
1. The path is resolved in the classpath (all JAR files and the `WEB-INF/classes` folder of the SMP web application)
2. If not found, the path is resolved in the file system. If the path is relative the resolution happens relative to the current base directory (which was `/var/lib/tomcat7` if I recall correctly)

-> That's why I recommend to provide an absolute path because the assumption is, that if the smp-server.properties file is provided externally, the keystore will also reside somewhere else.

Anyway the error message is not hard coded, but it is really what was read from the configuration file (since not default is present).

Please check your start-up logs to see from where the configuration file was loaded!

**Comment by OskarD** [comment]
It turns out I was looking at the wrong directory. I was changing the smp-server.properties found inside the `src/main/resources/` directory when I should have been changing inside the deployed directory.

I changed the path there to the absolute one and now it works. Thanks for the help Philip.
