### ISSUE TITLE
Improvements and futureabout peppol doubts

### ISSUE THREAD

**Issue by elfogre** [phax/peppol-smp-server#21]
Hello Philip,

I've been working in Peppol since https://github.com/phax/peppol-smp-server/issues/18 and currently we (Edicom) are Peppol AP and SMP for several interlocutors in Italy. I made some radical changes to the data model of your project that I want to share:

- We have a problem with a unique restriction on mysql with documentType identifier (varchar 500) because it's too long. We have added a hash column for the identifier, and we put a unique clause on hash and scheme.
- We have change relations between document, process, endpoint and servicemetadata. With previous datamodel you have lots of endpoint entries that just have the same info but different processes. Now we have a model with 1 to N relations between documentType, process, endpoint to serviceMetadata (I've added a datamodel diagram to clarify this).
- This change complicates the creation of SMP xml, so we have to change smpserver logic.

![peppoldm](https://cloud.githubusercontent.com/assets/13524391/15675556/cb3358d4-2742-11e6-92ae-0080025f772b.png)
[model.zip](https://github.com/phax/peppol-smp-server/files/291162/model.zip)

I have some questions about peppol directory and peppol and AS4 if you could kindly answer. Your oppinion could be very helpful.

Peppol directory will be work using your (actual) non-standard CompleteServiceGroupInterface?

AS4. SMP will have major changes? just add a new transportProfile and maybe some minor fields add for extra parameters?

I've seen that you are contributing to holodeck as4 implementation. Is it a nice project for AS4 transport in Peppol?

Thank you very much!

**Comment by phax** [comment]
Hi!
Thanks for the model - I will investigate this in more details.
Concerning your questions:
* PEPPOL Directory will use it's own "/businesscard" REST interface. This is an extension to the SMP but the specification is not yet published. But it's definitively not the `CompleteServiceGroup` interface.
* For AS4 in E-SENS we're using the SMP "as-is". But that's why I made the transport profiles editable, so they can be used in different scenarios as well.
* Holodeck: is a great implementation - I'm meeting Sander today and I will try to discuss with him, whether it would be possible to create a Servlet based implementation, as the current standalone Axis implementation is hard to integrate (at least for me). On the other hand there is Domibus but from my point of view it is overengineered (I would not use it because of it's dozens of dependencies etc.) 
hth, Philip

**Comment by elfogre** [comment]
Thank you Philip!

Your answers help me a lot to clarify the near future of Peppol and how to approach to its new features.

**Comment by phax** [comment]
The current version of the SMP has a "hidden" property to enable PEPPOL Directory support (`smp.peppol.directory.integration.enabled`) so you can check how it (could) work.

Concerning AS4: the developer of Holodeck is quite open to contributions -.you may consider this.

**Comment by elfogre** [comment]
Maybe integrate is not the apropiate word.

We have use your peppol-sbdh, peppol-sml-client, peppol-smp-client and ph-ubl libraries, but smp-server was more a reboot.
We have implemented our own server-library and server-sql with very similar interfaces to yours (they are nice, clean and clear), but we have some big changes:

- We use Spring, for example Transactions to DDBB were managed by Spring. In smlHook for example we catch spring transactions exceptions to rollback changes on EU SML. We use singleton beans and injection also, so implementations are quite different.
- We develope an extra interface for angular based web client.
- We have merged that code with our AS2 server.

Do you have a mailList or something similar to stay in touch with this Peppol news?

**Comment by phax** [comment]
Thanks for the information - I'm always curious what happens :)
There are the regular PEPPOL mailing lists (POACC, TICC etc.) and there is http://peppol.helger.com/public where I post some news from time to time but no big "PEPPOL integrator platform" :(
