### ISSUE TITLE
Intermittent Error When Creating New Participant Service Group

### ISSUE THREAD

**Issue by dhixon** [phax/peppol-smp-server#67]
Occasionally when I use the GUI or API to create a new participant it fails.  I was creating participants with ID's ending in 219, 220 and 221.  Sometimes they were successfully created and sometimes they were unsuccessful.  I saw a 401 in there from the SML for one attempt.  I then retried the attempt 
[logs.out.zip](https://github.com/phax/peppol-smp-server/files/1767637/logs.out.zip)

and it then worked.  I have attached the console log (catalina.out equivalent in docker world).

**Comment by phax** [comment]
`iso6523-actorid-upis::0009:43402724900219` was a read-timeout at the SML
`iso6523-actorid-upis::0009:70980187200041` was also a read-timeout at the SML (and so on)
==> I will increase the default read timeout time for SML calls

@dhixon: For the PEPPOL Directory you have a misconfigured keystore - please check file `pd-client.properties`. It must contains the same keystore as `smp-server.properties`.

The HTTP 400 call when trying to create `iso6523-actorid-upis::0009:43402724900219` might be because the ID was already registered in the SML by your SMP => https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0009%3A43402724900219&sml=auto&action=perform

Concerning the HTTP 401 (Unauthorized) for iso6523-actorid-upis::0009:43402724900220 - my interpretation is, that this participant is already registered. Checking at https://peppol.helger.com/public/locale-en_US/menuitem-tools-participant?scheme=iso6523-actorid-upis&value=0009%3A43402724900220&sml=auto&action=perform -> yes it is registered

**Comment by dhixon** [comment]
Thanks.  How do I get the read timeout fix?  Will that be a new release, or is there a way I can effect that on my existing SMP?

**Comment by phax** [comment]
According to https://docs.oracle.com/javase/7/docs/technotes/guides/net/properties.html you can set a default timeout: sun.net.client.defaultReadTimeout
No idea if this is supported by IBM JDK

Else wait for 5.0.4 - scheduled before end of march with PKI update as well

**Comment by dhixon** [comment]
Thanks Philip.  If you don't mind my asking, how did you know that there is a problem with PEPPOL Directory?

**Comment by phax** [comment]
```
[2018-02-06T09:49:30,278] [SMP-SERVER] [ERROR] [http-nio-8080-exec-3] Failed to initialize keystore for service connection! Can only use http now! Details: Failed to locate keystore path 'keystore/keystore.jks'. Technical details: Failed to open key store 'keystore/keystore.jks' -- com.helger.pd.client.PDHttpClientFactory.createSSLContext(PDHttpClientFactory.java:65)
```
