### ISSUE TITLE
Participant Identifiers, Document identifiers

### ISSUE THREAD

**Issue by achristofi** [phax/peppol-smp-server#68]
We have been testing phoss SMP Server (v5.0.3) for an e-Delivery project. 
The project falls under none of the CEF Policy Domains (eProcurement, eJustice, eHealth, …), so we will be using identifiers as close to the OASIS standards and the e-SENS profiles as possible.
There are two issues I would like to bring to your attention regarding the SMP:

1. Participant IDs:
- Our solution falls under none of the CEF Policy Domains (eProcurement, eJustice, eHealth, …) and we will be using the 'urn:oasis:names:tc:ebcore:partyid-type:iso6523:xxxx” or the “urn:oasis:names:tc:ebcore:partyid-type:unregistered:cyvat” participant identifier schemes. However, the corresponding MySQL column is too short to accommodate the scheme. When creating a ‘Service group’ we get:
- Error creating the new SMP ServiceGroup for participant 'urn:oasis:names:tc:ebcore:partyid-type:unregistered:cyvat::CY12345678X'. The same for: urn:oasis:names:tc:ebcore:partyid-type:iso6523:xxxx::CY12345678X
- The  error in the log reads: “…. Data truncation: Data too long for column 'businessIdentifierScheme' ….”
- The  error happens only for the “SQL” backend; when using the “XML” backend, which obviously places no size restrictions, the operation succeeds…

2. Document Types:
- Our Document schemas are in the form: http://cyprus.gov.cy/schema/edelivery/forms/v01
- We are able to create “Endpoints” using the SMP’s UI for documents like: “bdx-docid-qns::http://cyprus.gov.cy/schema/edelivery/forms/v01::doc0001cy”, but we get a “400 – Bad request” error when we try to GET the “ServiceMetadata”:
127.0.0.1 - - [06/Mar/2018:07:29:46 +0200] "GET /unregistered%3Acyreg%3A%3AHE123456/services/bdx-docid-qns%3A%3Ahttp%3A%2F%2Fcyprus.gov.cy%2Fschema%2Fedelivery%2Fforms%2Fv01%3A%3Adoc0001cy HTTP/1.1" 400 –
- Testing with “bdx-docid-qns::urn:cy:gov:schema:edelivery:docs:v01::doc0001cy” is OK!

**Comment by phax** [comment]
Dear @achristofi  there is a lot of input inside. Let me try to get it point by point
ad 1.)
* I personally recommend the XML backend - it does not have all the limitations and usually the amount of data in an SMP does not really get big
* The length of the column that is used in a key, having data type String, is limited by MySQL to 255 chars (or so), because in the worst case, each character can have up to 3 bytes  and the limit is 768 bytes (or so - I tried to remember the values from the top of my head)
* The SQL backend has other problems as well - the column names are too long for Oracle etc. I have plans to come up with a better backend, but SQL is not in my focus.....
* Concerning the error creating the service group - this requires a totally redesigned SQL backend.... Any PR is welcome :)

ad 2.)
* This depends on your Application Server configuration. Are you using Tomcat? If so, did you follow the rules at https://github.com/phax/peppol-smp-server/wiki/Apache-Tomcat ?

hth

**Comment by achristofi** [comment]
Dear Mr Helger,
Your prompt response is much appreciated.

1.	Thanks for your input, we will keep to the XML backend
2.	Indeed the error was a misconfiguration (spelling mistake :) )

Friendly regards
