### ISSUE TITLE
Deletion of Business Card

### ISSUE THREAD

**Issue by emilbokenstrand** [phax/peppol-smp-server#69]
Greetings,

When I delete a Business Card (from GUI) I can still find the company in Peppol Directory Search. My guess would be that it should be deleted from there? I am able to add a Business Card again and change the data and this is reflected to the PD search but my deletion is not. My tests were made with PEPPOL Directory hostname: https://test-directory.peppol.eu

Regards

Emil

**Comment by phax** [comment]
Hi Emil,
what version are you currently using?
Please make sure to use v5.0.4 of the SMP. That should resolve the issue.
Thanks

**Comment by emilbokenstrand** [comment]
Hi Philip,

Thanks for the fast reply. I am running 5.0.4 but the Business Card and the Peppol Directory entry was first created on 5.0.3. I added a second entity (on the same participant) just now and then deleted it and that worked fine. I am also able to edit the PD by adding a Business Card again. I can also delete the first Entity by adding a new one and removing the first. It seems I always fail on deleting the last entity of the PD.

I then tried addind a new Service Group (and an endpoint) and created a Business Card. Then I deleted the Service Group but also in this case it still shows up in the PD. 

Thanks for assisting

**Comment by phax** [comment]
Mea culpa. There is currently a "timing issue" in the PD that hinders entries from getting removed - I always forget this.
First the PD deletion is triggered, than the entry is removed from the SML. In certain cases the PD tries to make a DNS lookup for the deleted entry (I need to fix this) and fails. That's why the entry is not deleted. If you drop me a note, which entry is affected, I can delete it manually.

**Comment by phax** [comment]
Fixed in 5.0.5 release
